### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by Devy001** [adepierre/Caffe_CycleGAN#2]
Hi, Can you share your trained model? Thank you!

**Comment by adepierre** [comment]
Hi,

I have changed the architecture of the network, so I don't have a fully trained model for the latest architecture. But if you revert to commit 706073e69d2f7cb7a242e1d10787b576e41bf097 you should have access to the prototxt and the caffemodel files to reproduce the results shown in the readme.

**Comment by Devy001** [comment]
Thank you, I willl have a try.
