### ISSUE TITLE
How to run in Linux?

### ISSUE THREAD

**Issue by o0t1ng0o** [adepierre/Caffe_CycleGAN#3]
Hi, @adepierre 
I really appreciate your work~
But, i want to know how can i use it in Linux.

Could you please give me more details for running in Linux?
Many thanks!

Valentina

**Comment by adepierre** [comment]
Hi!

Well, there is normally nothing specific to Windows in the code, so you should be able to compile it in Linux without any trouble.

First, you should build and install Caffe with the modification explained in the Dependencies part of the Readme.

Then you just have to clone this repo and use Cmake for the build.

**Comment by o0t1ng0o** [comment]
Thanks! @adepierre 
I found it can run in Linux.
But, unfortunately i found the following problem when i run main.cpp.
I0711 22:03:20.806023 41867 net.cpp:84] Creating Layer Cyclic_loss_diff
I0711 22:03:20.806030 41867 net.cpp:406] Cyclic_loss_diff <- generator_output
I0711 22:03:20.806036 41867 net.cpp:406] Cyclic_loss_diff <- cyclic_input
I0711 22:03:20.806042 41867 net.cpp:380] Cyclic_loss_diff -> cyclic_diff
F0711 22:03:20.806062 41867 eltwise_layer.cpp:34] Check failed: bottom[0]->shape() == bottom[i]->shape() bottom[0]: 1 1 256 256 (65536), bottom[1]: 1 3 256 256 (196608)
*** Check failure stack trace: ***
    @     0x7fae43e1b5cd  google::LogMessage::Fail()
    @     0x7fae43e1d433  google::LogMessage::SendToLog()
    @     0x7fae43e1b15b  google::LogMessage::Flush()
    @     0x7fae43e1de1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fae4aa0600c  caffe::EltwiseLayer<>::Reshape()
    @     0x7fae4a99efa7  caffe::Net<>::Init()
    @     0x7fae4a9a16de  caffe::Net<>::Net()
    @     0x7fae4aaeda6a  caffe::Solver<>::InitTrainNet()
    @     0x7fae4aaeef35  caffe::Solver<>::Init()
    @     0x7fae4aaef24f  caffe::Solver<>::Solver()
    @     0x7fae4ab0a941  caffe::Creator_AdamSolver<>()
    @           0x42062f  caffe::SolverRegistry<>::CreateSolver()
    @           0x41cd53  NN_Agent::NN_Agent()
    @           0x4059c5  main
    @     0x7fae431c5830  __libc_start_main
    @           0x40a649  _start
    @              (nil)  (unknown)
Aborted (core dumped)

Is there any problem in the generator network?
I would appreciate a lot if you reply~~  ^_^
Thanks~~

**Comment by adepierre** [comment]
It's very strange that the generator_output blob has only 1 channel. Did you change anything in the code to use the net on grayscale images?

If you did, then you also need to set the number of channels to 1 in the cyclic input layer (https://github.com/adepierre/Caffe_CycleGAN/blob/master/src/main.cpp#L487) and in the normalization of the cyclic loss (https://github.com/adepierre/Caffe_CycleGAN/blob/master/src/main.cpp#L533)

If not, please tell me what you did exactly and I will try to find if there is a bug in the code.

**Comment by o0t1ng0o** [comment]
I only set the path for the images in main.cpp and compile the file. 
All my images have 3 channels.
I didn't modify anything in the code~

**Comment by adepierre** [comment]
There was indeed a bug in src/main.cpp, I guess I tried with grayscale images before the last commit.

Please replace line 466 

<< ConvolutionLayer("Generator_Conv4", "generator_Deconv2", "generator_pre_output", **1**, 7, 1, 3, train, false);

with the following:

<< ConvolutionLayer("Generator_Conv4", "generator_Deconv2", "generator_pre_output", **3**, 7, 1, 3, train, false);

I will fix it in the repo later.

**Comment by o0t1ng0o** [comment]
thanks a lot~
｡◕‿◕｡
