### ISSUE TITLE
Training breaks down after 100000 iterations

### ISSUE THREAD

**Issue by inkzk** [adepierre/Caffe_CycleGAN#5]
No bugs found, and the `solver prototxt` is OK, any ideas？

**Comment by adepierre** [comment]
Hmmm, could you provide more details on your problem?

Is there anything written in the console? How many images do you have in your dataset and how many epoch did you ask the code to run? For example, with a dataset of 1000 images, a batch size of 1 and 100 epochs it's just normal that the code stops after 100000 iterations.

Do you have the A_to_B.png and B_to_A.png images? If yes it means the training has just ended normally.
